version: "3.8"
services:
    conexion_ambulancia:
        container_name: conexion_ambulancia_v1
        build: .
        ports:
            - "39000:9000"
            - "38900:8090"
        environment: 
            DATABASE_URL: "jdbc:postgresql://dpg-clmu0n38772c73e1mcr0-a.oregon-postgres.render.com/conexion_ambulancia_5fw6"
            DATABASE_USERNAME: "conexion_ambulancia_5fw6_user"
            DATABASE_PASSWORD: "flluX92IwTLzp0J8BvJjD53pPWmF35c9"
        networks:
            - jenkins
networks:
    jenkins:
        name: jenkins
        external: true

volumes:
    conexion_ambulancia_data: 